version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
